version: '3.9'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '8080:80'
    restart: always
    stdin_open: true
    tty: true
  api:
    build:
      context: ./server-api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server-api:/app
    restart: always
    stdin_open: true
    tty: true
    ports:
      - '5858:5858'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis:latest
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379:6379'
    volumes:
      - ./redis-storage-persistent:/data
